---
spring:
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: SAMPLE-HYSTRIX-CONFIG

eureka:
  instance:
    nonSecurePort: ${server.port:8089}
  client:
    serviceUrl:
      defaultZone: http://34.226.152.44:8761/eureka
#      defaultZone: http://18.212.48.4:8761/eureka
